FROM openjdk:8-jre-alpine
#设置容器时间与宿主时间一致
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apk add --update font-adobe-100dpi ttf-dejavu fontconfig
ADD *.jar app.jarENTRYPOINT exec java $JAVA_OPTS   -Djava.security.egd=file:/dev/./urandom  -jar /auth-server.jar
